name: DocFX docs Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  generate-docs:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.100
      - name: Install dependencies
        run: dotnet restore
      - name: .NET build
        run: dotnet build --configuration Release
      - name: Run DocFX
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docs/docfx.json
      - name: Install the DFMG tool
        run: dotnet tool install -g DocFxMarkdownGen
      - name: Generate DFMG markdown
        run: cd docs && dfmg
      - name: Set up NPM
        uses: bahmutov/npm-install@v1
        with:
          working-directory: docs
      - name: Copy static files to documentation
        run: cp -R static_docs/* docs/src/pages/guides
      - name: Build docusaurus
        run: cd docs && npm run build
      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          cname: copper.maxus.space
          force_orphan: true
